apiVersion: v1
kind: Pod
metadata:
  name: dnstool
  namespace: default
spec:
  containers:
  - image: infoblox/dnstools:latest
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: dnstool
  restartPolicy: Always
