apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    service: web
    version: "1.7.9"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http

