apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc
  labels:
    app: sonarqube-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi