apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions-pvc
  labels:
    app: sonarqube-extensions
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
