apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  type: LoadBalancer
  ports:
    - name: sonarport
      port: 8082
      targetPort: 9000
  selector:
    app: sonarqube
