apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-and-pod-logs-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-and-pod-logs-reader
roleRef:
  kind: ClusterRole
  name: pod-and-pod-logs-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: default
  name: cluster-pod-reader
---

