apiVersion: v1
kind: Pod
metadata:
  name: proxy-chk
  namespace: project1
spec:
  containers:
  - name: centos
    image: centos
    command: ["/bin/sh", "-c", "while : ;do curl -L http://${GOOGLE_PROXY_SERVICE_HOST}:80/; sleep 10; done"]

