kind: Service
apiVersion: v1
metadata:
  name: nginx-nodeport
  namespace: project1
spec:
  type: NodePort
  selector:
    project: lab7
    service: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http

