apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hugo-app-blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hugo-app-canary
        track: canary
    spec:
      containers:
        - name: hugo-app
          image: sureshchandrarhca15/hugo-app:blue
          ports:
            - containerPort: 80

