apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
   - targetPort: {{ .Values.server.port }}
     port: {{ .Values.server.port }}
  selector:
   app: {{ .Values.server.name }}
   type: front-end
